name: AutoHack Test Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install dependencies for testing
      run: |
        pip install -r requirements_test.txt
    - name: Lint with flake8
      run: |
        flake8 src/autohack
    - name: Run testcases
      run: |
        pytest .